# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---

include:
  - board: nice_nano
    shield: vranger24-keyboard
    artifact-name: vranger24_keyboard

name: Build ZMK Firmware

on:
  push:
    paths:
      - 'zmk/**'
      - '.github/workflows/build.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip cmake ninja-build git wget unzip

    - name: Install West
      run: pip3 install west

    - name: Install Zephyr SDK
      run: |
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.2/zephyr-sdk-0.16.2-linux-x86_64-setup.run -O zephyr-sdk.run
        chmod +x zephyr-sdk.run
        ./zephyr-sdk.run -- -d $HOME/zephyr-sdk
        echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV

    - name: Initialize ZMK and Zephyr
      run: |
        west init -l zmk
        west update
        west zephyr-export
      env:
        ZEPHYR_SDK_INSTALL_DIR: ${{ env.ZEPHYR_SDK_INSTALL_DIR }}

    - name: Build firmware
      run: |
        west build -b nice_nano -d build \
          -- -DZMK_CONFIG=config -DSHIELD=vranger24-keyboard \
          -DZMK_EXTRA_MODULES=$(pwd)/zmk
